name: parq
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - einops=0.4.1
  - matplotlib=3.6.2
  - numpy=1.23.3
  - omegaconf=2.2.3
  - opencv=4.5.5
  - pillow=9.2.0
  - pip=22.3
  - python=3.9.13
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - cudatoolkit=11.6.0
  - yacs=0.1.8
  - pip:
    - pytorch-lightning==1.6.5
    - scipy==1.9.3
    - tensorboard==2.10.1
    - numba==0.57.1
    - scikit-learn
    - colorama
